# curl -H 'Client-ID: 0m7mjx5gk0km1ucct94bbafd0qub1s' \
# -X GET 'https://api.twitch.tv/helix/streams?game_id=21779'

# curl -H 'Client-ID: 0m7mjx5gk0km1ucct94bbafd0qub1s' \
# -X GET 'https://api.twitch.tv/helix/games/top'

curl -H 'Client-ID: 0m7mjx5gk0km1ucct94bbafd0qub1s' \
-X GET 'https://api.twitch.tv/helix/games?name=League of legends'