const SET_TOP_GAMES = "SET_TOP_GAMES";
const SET_GAME_STREAMS = "SET_GAME_STREAMS";
const SET_FILTER = "SET_FILTER";
const REMOVE_FILTER = "REMOVE_FILTER";
const SET_GAME_FETCH_LOADING = "SET_GAME_FETCH_LOADING";
const SET_SEARCHED_GAME = "SET_SEARCHED_GAME";
const SET_SEARCH_ERROR = "SET_SEARCH_ERROR";

export {
  SET_TOP_GAMES,
  SET_GAME_STREAMS,
  SET_FILTER,
  REMOVE_FILTER,
  SET_GAME_FETCH_LOADING,
  SET_SEARCHED_GAME,
  SET_SEARCH_ERROR
};
